apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-c
  labels:
    app: servico-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servico-c
  template:
    metadata:
      labels:
        app: servico-c
    spec:
      containers:
      - name: servico-c
        image: servico-c:latest # Imagem Docker do serviço C
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: servico-c
spec:
  selector:
    app: servico-c
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort
